from . import main_handler
from . import registr_handler
from . import order_handler
from . import updata_data_handler
from . import admin_login
from . import admin_orders_handlers
from . import password
from . import settings_handler
from . import question_edit_handler